apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport-svc
  namespace: storage
spec:
  type: NodePort
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: minio # must match with the label used in minio deployment
