kind: Pod
apiVersion: v1
metadata:
  name: osm-pod
  namespace: demo
spec:
  restartPolicy: Never
  containers:
  - name: osm
    image: appscodeci/osm
    env:
    - name: PROVIDER
      value: s3
    - name: AWS_ENDPOINT
      value: https://minio.demo.svc
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-client-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-client-secret
          key: AWS_SECRET_ACCESS_KEY
    - name: CA_CERT_FILE
      value: /etc/minio/certs/ca.crt # root ca has been mounted here
    args:
    - "mc internal-bucket" # create a bucket named "internal-bucket"
    volumeMounts: # mount root ca in /etc/minio/certs directory
    - name: credentials
      mountPath: /etc/minio/certs
  volumes:
  - name: credentials
    secret:
      secretName:  minio-client-secret
      items:
      - key: ca.crt
        path: ca.crt
