apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  - prometheusrules
  verbs: ["*"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs: ["list", "watch"]
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["list","delete"]
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs: ["get","create","update"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["list","watch"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get","list","watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
