apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.98.52.204"
    path: "/pvc" # "pvc" folder must exist in "/exports" directory of NFS server
